version: '3.5'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - '80:80'
  api:
    hostname: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/go/src/github.com/josepablo93/api
  client:
    hostname: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/node_modules:/app/nodemodules
      - ./client:/app
